apiVersion: v1
kind: Service
metadata:  
  labels:
    app: greeting-dplmnt
  name: greeting-svc
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30899
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: greeting-dplmnt
  sessionAffinity: None
  type: NodePort

